services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: medscheduler-api

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - ./src/.env

    depends_on:
      - postgres

    restart: unless-stopped

  postgres:
    image: postgres:17

    container_name: medscheduler-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: medscheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: